# Generated by Django 6.1 on 2026-09-01 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(choices=[('CREATE', 'Tambah'), ('UPDATE', 'Ubah'), ('DELETE', 'Hapus')], max_length=10)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.IntegerField(null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Audit',
                'verbose_name_plural': 'Log Audit',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Nakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('profesi', models.CharField(choices=[('ATLM', 'ATLM (Teknisi Laboratorium Medik)'), ('Radiografer', 'Radiografer'), ('Fisioterapis', 'Fisioterapis'), ('Nutrisionis', 'Nutrisionis'), ('Perekam Medis', 'Perekam Medis'), ('Apoteker', 'Apoteker'), ('Sanitarian', 'Sanitarian'), ('Lainnya', 'Lainnya')], max_length=50)),
                ('unit_kerja', models.CharField(max_length=200)),
                ('no_str', models.CharField(max_length=50, unique=True, verbose_name='Nomor STR')),
                ('masa_berlaku_str', models.DateField(verbose_name='Masa Berlaku STR')),
                ('no_sip', models.CharField(max_length=50, unique=True, verbose_name='Nomor SIP')),
                ('masa_berlaku_sip', models.DateField(verbose_name='Masa Berlaku SIP')),
                ('status_kredensial', models.CharField(choices=[('Belum Pengajuan', 'Belum Pengajuan'), ('Dalam Proses', 'Dalam Proses'), ('Selesai', 'Selesai')], default='Belum Pengajuan', max_length=20)),
                ('kewenangan_klinis', models.CharField(choices=[('Aktif', 'Aktif'), ('Evaluasi', 'Evaluasi'), ('Proses', 'Proses'), ('Tidak Aktif', 'Tidak Aktif')], default='Proses', max_length=20)),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nakes_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenaga Kesehatan',
                'verbose_name_plural': 'Tenaga Kesehatan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='DokumenNakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('STR', 'Surat Tanda Registrasi'), ('SIP', 'Surat Izin Praktik'), ('Sertifikat', 'Sertifikat Kredensial'), ('Lainnya', 'Lainnya')], max_length=20)),
                ('nama_file', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='dokumen/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('nakes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='nakes.nakes')),
            ],
            options={
                'verbose_name': 'Dokumen',
                'verbose_name_plural': 'Dokumen',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
