# Generated by Django 6.1 on 2026-09-04 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumenUmum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('kategori', models.CharField(choices=[('SOP', 'SOP (Standar Operasional Prosedur)'), ('SK', 'Surat Keputusan'), ('Panduan', 'Panduan / Pedoman'), ('Formulir', 'Formulir'), ('Kebijakan', 'Kebijakan'), ('Lainnya', 'Lainnya')], max_length=20)),
                ('deskripsi', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='dokumen_umum/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dokumen Umum',
                'verbose_name_plural': 'Dokumen Umum',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
