# Generated by Django 6.1 on 2026-09-09 15:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakes', '0003_profesi_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluasiMutuKlinis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_kerja', models.CharField(max_length=200, verbose_name='Unit / Instalasi')),
                ('periode_bulan', models.PositiveSmallIntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Maret'), (4, 'April'), (5, 'Mei'), (6, 'Juni'), (7, 'Juli'), (8, 'Agustus'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Desember')], verbose_name='Bulan')),
                ('periode_tahun', models.PositiveIntegerField(verbose_name='Tahun')),
                ('nama_indikator', models.CharField(max_length=300, verbose_name='Nama Indikator Mutu')),
                ('standar_target', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Standar Target (%)')),
                ('capaian', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Capaian (%)')),
                ('analisis', models.TextField(blank=True, verbose_name='Analisis')),
                ('rencana_tindak_lanjut', models.TextField(blank=True, verbose_name='Rencana Tindak Lanjut (RTL)')),
                ('penanggung_jawab', models.CharField(blank=True, max_length=200, verbose_name='Penanggung Jawab / PIC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutu_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluasi Mutu Layanan Klinis',
                'verbose_name_plural': 'Evaluasi Mutu Layanan Klinis',
                'ordering': ['-periode_tahun', '-periode_bulan', 'unit_kerja'],
            },
        ),
        migrations.CreateModel(
            name='EvaluasiOPPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveIntegerField(verbose_name='Tahun Evaluasi')),
                ('tanggal_evaluasi', models.DateField(verbose_name='Tanggal Evaluasi')),
                ('skor_perilaku_1', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skor_perilaku_2', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skor_perilaku_3', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skor_perilaku_4', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skor_perilaku_5', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skor_perilaku_6', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skor_perilaku_7', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skor_profesional_1', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skor_profesional_2', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skor_profesional_3', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skor_profesional_4', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skor_kinerja_1', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skor_kinerja_2', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skor_kinerja_3', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skor_kinerja_4', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skor_kinerja_5', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skor_kinerja_6', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skor_kinerja_7', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skor_kinerja_8', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skor_kinerja_9', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_nilai', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7, verbose_name='Total Nilai')),
                ('poin_penilaian', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, verbose_name='Poin Penilaian')),
                ('grade', models.CharField(choices=[('B', 'Baik'), ('C', 'Cukup'), ('K', 'Kurang')], default='K', editable=False, max_length=1, verbose_name='Grade')),
                ('penilai_nama', models.CharField(blank=True, max_length=200, verbose_name='Nama Penilai / Atasan Langsung')),
                ('penilai_nip', models.CharField(blank=True, max_length=50, verbose_name='NIP Penilai')),
                ('mengetahui_nama', models.CharField(blank=True, max_length=200, verbose_name='Nama Manajer / Ka. Instalasi')),
                ('mengetahui_nip', models.CharField(blank=True, max_length=50, verbose_name='NIP Manajer / Ka. Instalasi')),
                ('pegawai_nip', models.CharField(blank=True, max_length=50, verbose_name='NIP Pegawai yang Dinilai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oppe_created', to=settings.AUTH_USER_MODEL)),
                ('nakes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oppe_set', to='nakes.nakes', verbose_name='Tenaga Kesehatan')),
            ],
            options={
                'verbose_name': 'Evaluasi OPPE',
                'verbose_name_plural': 'Evaluasi OPPE',
                'ordering': ['-tahun', '-tanggal_evaluasi'],
                'unique_together': {('nakes', 'tahun')},
            },
        ),
    ]
