# Generated by Django 6.1 on 2026-09-10 01:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakes', '0004_evaluasimutuklinis_evaluasioppe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PelanggaranEtik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_kejadian', models.DateField(verbose_name='Tanggal Kejadian')),
                ('tanggal_lapor', models.DateField(default=datetime.date.today, verbose_name='Tanggal Dilaporkan')),
                ('kategori', models.CharField(choices=[('Ringan', 'Ringan'), ('Sedang', 'Sedang'), ('Berat', 'Berat')], default='Ringan', max_length=20, verbose_name='Kategori Pelanggaran')),
                ('deskripsi', models.TextField(verbose_name='Catatan / Kronologi Pelanggaran')),
                ('pelapor', models.CharField(blank=True, max_length=200, verbose_name='Nama Pelapor / Sumber Informasi')),
                ('status', models.CharField(choices=[('Menunggu Tindak Lanjut', 'Menunggu Tindak Lanjut'), ('Dalam Investigasi', 'Dalam Investigasi'), ('Diteruskan ke Sidang', 'Diteruskan ke Sidang'), ('Selesai', 'Selesai')], default='Menunggu Tindak Lanjut', max_length=30, verbose_name='Status Tindak Lanjut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pelanggaran_created', to=settings.AUTH_USER_MODEL)),
                ('nakes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelanggaran_etik_set', to='nakes.nakes', verbose_name='Tenaga Kesehatan')),
            ],
            options={
                'verbose_name': 'Pelanggaran Etik',
                'verbose_name_plural': 'Pelanggaran Etik',
                'ordering': ['-tanggal_kejadian', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SidangEtik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_sidang', models.CharField(max_length=250, verbose_name='Agenda / Judul Sidang')),
                ('tanggal_sidang', models.DateField(verbose_name='Tanggal Sidang')),
                ('waktu_mulai', models.TimeField(verbose_name='Waktu Mulai')),
                ('waktu_selesai', models.TimeField(blank=True, null=True, verbose_name='Waktu Selesai')),
                ('tempat', models.CharField(default='Ruang Rapat Komite Etik', max_length=200, verbose_name='Tempat / Ruangan')),
                ('perangkat_sidang', models.TextField(blank=True, verbose_name='Perangkat Sidang (Ketua, Sekretaris, Anggota)')),
                ('status', models.CharField(choices=[('Terjadwal', 'Terjadwal'), ('Selesai', 'Selesai'), ('Ditunda', 'Ditunda'), ('Dibatalkan', 'Dibatalkan')], default='Terjadwal', max_length=20, verbose_name='Status Sidang')),
                ('hasil_investigasi', models.TextField(blank=True, verbose_name='Hasil Investigasi / Fakta Sidang')),
                ('rekomendasi_pembinaan', models.TextField(blank=True, verbose_name='Rekomendasi Pembinaan')),
                ('tindak_lanjut', models.TextField(blank=True, verbose_name='Tindak Lanjut Eksekusi Pembinaan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sidang_created', to=settings.AUTH_USER_MODEL)),
                ('nakes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sidang_etik_set', to='nakes.nakes', verbose_name='Tenaga Kesehatan Terperiksa')),
                ('pelanggaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sidang_set', to='nakes.pelanggaranetik', verbose_name='Pelanggaran Terkait')),
            ],
            options={
                'verbose_name': 'Sidang Etik',
                'verbose_name_plural': 'Sidang Etik',
                'ordering': ['tanggal_sidang', 'waktu_mulai'],
            },
        ),
        migrations.CreateModel(
            name='EvaluasiKinerjaEtik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_tahun', models.PositiveIntegerField(verbose_name='Tahun Evaluasi')),
                ('periode_semester', models.PositiveSmallIntegerField(choices=[(1, 'Semester 1 (Januari - Juni)'), (2, 'Semester 2 (Juli - Desember)')], verbose_name='Semester')),
                ('predikat', models.CharField(choices=[('Sangat Baik', 'Sangat Baik'), ('Baik', 'Baik'), ('Cukup', 'Cukup'), ('Kurang', 'Kurang')], default='Baik', max_length=20, verbose_name='Predikat Kinerja Etik')),
                ('status_kepatuhan', models.CharField(choices=[('Patuh', 'Patuh (Tanpa Catatan)'), ('Dalam Pembinaan', 'Dalam Pembinaan'), ('Sanksi Aktif', 'Sanksi Aktif')], default='Patuh', max_length=30, verbose_name='Status Kepatuhan Etik')),
                ('catatan_evaluasi', models.TextField(verbose_name='Catatan Evaluasi Perilaku & Etika')),
                ('rekomendasi_kelanjutan', models.TextField(blank=True, verbose_name='Rekomendasi Kelanjutan Kewenangan / SPK')),
                ('evaluator', models.CharField(blank=True, max_length=200, verbose_name='Nama Evaluator / Penilai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluasi_etik_created', to=settings.AUTH_USER_MODEL)),
                ('nakes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluasi_etik_set', to='nakes.nakes', verbose_name='Tenaga Kesehatan')),
            ],
            options={
                'verbose_name': 'Evaluasi Kinerja Etik',
                'verbose_name_plural': 'Evaluasi Kinerja Etik',
                'ordering': ['-periode_tahun', '-periode_semester', 'nakes__nama'],
                'unique_together': {('nakes', 'periode_tahun', 'periode_semester')},
            },
        ),
    ]
