# Generated by Django 6.1 on 2026-09-10 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakes', '0005_pelanggaranetik_sidangetik_evaluasikinerjaetik'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaRapat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_rapat', models.CharField(max_length=250, verbose_name='Judul / Agenda Rapat')),
                ('jenis_rapat', models.CharField(choices=[('Rapat Pleno', 'Rapat Pleno'), ('Rutin Bulanan', 'Rutin Bulanan'), ('Koordinasi', 'Koordinasi'), ('Insidentil', 'Insidentil'), ('Lainnya', 'Lainnya')], default='Rutin Bulanan', max_length=30, verbose_name='Jenis Rapat')),
                ('tanggal_rapat', models.DateField(verbose_name='Tanggal Rapat')),
                ('waktu_mulai', models.TimeField(verbose_name='Waktu Mulai')),
                ('waktu_selesai', models.TimeField(blank=True, null=True, verbose_name='Waktu Selesai')),
                ('tempat', models.CharField(default='Ruang Rapat Komite KTKL', max_length=200, verbose_name='Tempat / Ruangan')),
                ('peserta', models.TextField(blank=True, verbose_name='Daftar Peserta / Undangan')),
                ('status', models.CharField(choices=[('Terjadwal', 'Terjadwal'), ('Selesai', 'Selesai'), ('Ditunda', 'Ditunda'), ('Dibatalkan', 'Dibatalkan')], default='Terjadwal', max_length=20, verbose_name='Status')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan Tambahan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agenda Rapat',
                'verbose_name_plural': 'Agenda Rapat',
                'ordering': ['tanggal_rapat', 'waktu_mulai'],
            },
        ),
        migrations.CreateModel(
            name='NotulenRapat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=250, verbose_name='Judul Notulen')),
                ('tanggal', models.DateField(verbose_name='Tanggal Rapat')),
                ('waktu_mulai', models.TimeField(blank=True, null=True, verbose_name='Waktu Mulai')),
                ('waktu_selesai', models.TimeField(blank=True, null=True, verbose_name='Waktu Selesai')),
                ('tempat', models.CharField(blank=True, max_length=200, verbose_name='Tempat')),
                ('pimpinan_rapat', models.CharField(max_length=200, verbose_name='Pimpinan Rapat')),
                ('notulis', models.CharField(max_length=200, verbose_name='Notulis / Pencatat')),
                ('peserta_hadir', models.TextField(blank=True, verbose_name='Daftar Hadir Peserta')),
                ('agenda_bahasan', models.TextField(verbose_name='Agenda / Topik Bahasan')),
                ('isi_pembahasan', models.TextField(verbose_name='Isi Pembahasan')),
                ('kesimpulan_keputusan', models.TextField(verbose_name='Kesimpulan & Keputusan')),
                ('rencana_tindak_lanjut', models.TextField(blank=True, verbose_name='Rencana Tindak Lanjut & PIC')),
                ('file_lampiran', models.FileField(blank=True, null=True, upload_to='notulen/%Y/%m/', verbose_name='File Lampiran')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agenda_rapat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notulen_set', to='nakes.agendarapat', verbose_name='Agenda Rapat Terkait')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notulen_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notulen Rapat',
                'verbose_name_plural': 'Notulen Rapat',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Regulasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=250, verbose_name='Judul Dokumen Regulasi')),
                ('nomor_dokumen', models.CharField(max_length=100, verbose_name='Nomor Dokumen')),
                ('kategori', models.CharField(choices=[('SK Direktur', 'SK Direktur'), ('Pedoman / Panduan', 'Pedoman / Panduan'), ('SPO', 'SPO'), ('Kebijakan RS', 'Kebijakan Rumah Sakit'), ('Peraturan Perundangan', 'Peraturan Perundangan'), ('Lainnya', 'Lainnya')], default='SK Direktur', max_length=30, verbose_name='Kategori')),
                ('tanggal_terbit', models.DateField(verbose_name='Tanggal Terbit')),
                ('tanggal_berlaku', models.DateField(verbose_name='Tanggal Mulai Berlaku')),
                ('tanggal_kadaluarsa', models.DateField(blank=True, null=True, verbose_name='Tanggal Kadaluarsa')),
                ('status', models.CharField(choices=[('Berlaku', 'Berlaku'), ('Dalam Revisi', 'Dalam Revisi'), ('Dicabut', 'Dicabut')], default='Berlaku', max_length=20, verbose_name='Status Keabsahan')),
                ('ringkasan', models.TextField(blank=True, verbose_name='Ringkasan / Abstrak')),
                ('file', models.FileField(upload_to='regulasi/%Y/%m/', verbose_name='File Dokumen (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regulasi_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regulasi & Kebijakan',
                'verbose_name_plural': 'Regulasi & Kebijakan',
                'ordering': ['-tanggal_terbit'],
            },
        ),
    ]
